version: "3"
services:
  # name of service
  postgres:
    # image to run
    image: "postgres:latest"
  redis:
    image: "redis:latest"
    # proxy service
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    # should be done in aws config file as well
    ports:
      - "3050:80"
  api:
    build:
      # name of the docker file
      dockerfile: Dockerfile.dev
      # where to find the docker file and the other files
      context: ./server
      # volumes
    volumes:
      # leave that folder as is
      - /app/node_modules
      # copy everything of the server directory into
      # the app directory of the container except for the node_modules
      - ./server:/app
    environment:
      # name of the service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
